/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreatePayslipInput {
  'month' : string,
  'professionTax' : bigint,
  'employeeUsername' : string,
  'employeeName' : string,
  'ifscCode' : string,
  'dateOfBirth' : string,
  'designation' : string,
  'year' : bigint,
  'businessUnit' : string,
  'bankName' : string,
  'dateOfJoining' : string,
  'insurance' : bigint,
  'incentivePayable' : bigint,
  'employeeId' : EmployeeId,
  'aadharNumber' : string,
  'paymentMode' : string,
  'basicPayable' : bigint,
  'accountNumber' : string,
  'panNo' : string,
  'incentiveActual' : bigint,
  'basicActual' : bigint,
  'location' : string,
  'daysPaid' : bigint,
  'mobileAllowanceActual' : bigint,
  'mobileAllowancePayable' : bigint,
}
export interface Employee {
  'username' : string,
  'userId' : EmployeeId,
  'createdAt' : Time,
  'fullName' : string,
}
export type EmployeeId = bigint;
export interface Payslip {
  'month' : string,
  'payslipId' : PayslipId,
  'professionTax' : bigint,
  'totalDeductions' : bigint,
  'employeeUsername' : string,
  'employeeName' : string,
  'ifscCode' : string,
  'dateOfBirth' : string,
  'designation' : string,
  'createdAt' : bigint,
  'year' : bigint,
  'businessUnit' : string,
  'bankName' : string,
  'dateOfJoining' : string,
  'insurance' : bigint,
  'netPayable' : bigint,
  'incentivePayable' : bigint,
  'totalEarningsPayable' : bigint,
  'employeeId' : EmployeeId,
  'aadharNumber' : string,
  'paymentMode' : string,
  'basicPayable' : bigint,
  'accountNumber' : string,
  'panNo' : string,
  'incentiveActual' : bigint,
  'basicActual' : bigint,
  'location' : string,
  'daysPaid' : bigint,
  'mobileAllowanceActual' : bigint,
  'mobileAllowancePayable' : bigint,
  'totalEarningsActual' : bigint,
}
export type PayslipId = bigint;
export interface RegisterEmployeeInput {
  'username' : string,
  'fullName' : string,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'role' : string,
  'fullName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPayslip' : ActorMethod<[CreatePayslipInput], PayslipId>,
  'deletePayslip' : ActorMethod<[PayslipId], undefined>,
  'getAllPayslips' : ActorMethod<[], Array<Payslip>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[EmployeeId], [] | [Employee]>,
  'getPayslip' : ActorMethod<[PayslipId], [] | [Payslip]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllEmployees' : ActorMethod<[], Array<Employee>>,
  'listAllPayslips' : ActorMethod<[], Array<Payslip>>,
  'listPayslipsByEmployee' : ActorMethod<[string], Array<Payslip>>,
  'registerEmployee' : ActorMethod<[RegisterEmployeeInput], EmployeeId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];