/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmployeeId = IDL.Nat;
export const CreatePayslipInput = IDL.Record({
  'month' : IDL.Text,
  'professionTax' : IDL.Int,
  'employeeUsername' : IDL.Text,
  'employeeName' : IDL.Text,
  'ifscCode' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'designation' : IDL.Text,
  'year' : IDL.Nat,
  'businessUnit' : IDL.Text,
  'bankName' : IDL.Text,
  'dateOfJoining' : IDL.Text,
  'insurance' : IDL.Int,
  'incentivePayable' : IDL.Int,
  'employeeId' : EmployeeId,
  'aadharNumber' : IDL.Text,
  'paymentMode' : IDL.Text,
  'basicPayable' : IDL.Int,
  'accountNumber' : IDL.Text,
  'panNo' : IDL.Text,
  'incentiveActual' : IDL.Int,
  'basicActual' : IDL.Int,
  'location' : IDL.Text,
  'daysPaid' : IDL.Int,
  'mobileAllowanceActual' : IDL.Int,
  'mobileAllowancePayable' : IDL.Int,
});
export const PayslipId = IDL.Nat;
export const Payslip = IDL.Record({
  'month' : IDL.Text,
  'payslipId' : PayslipId,
  'professionTax' : IDL.Int,
  'totalDeductions' : IDL.Int,
  'employeeUsername' : IDL.Text,
  'employeeName' : IDL.Text,
  'ifscCode' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'designation' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'businessUnit' : IDL.Text,
  'bankName' : IDL.Text,
  'dateOfJoining' : IDL.Text,
  'insurance' : IDL.Int,
  'netPayable' : IDL.Int,
  'incentivePayable' : IDL.Int,
  'totalEarningsPayable' : IDL.Int,
  'employeeId' : EmployeeId,
  'aadharNumber' : IDL.Text,
  'paymentMode' : IDL.Text,
  'basicPayable' : IDL.Int,
  'accountNumber' : IDL.Text,
  'panNo' : IDL.Text,
  'incentiveActual' : IDL.Int,
  'basicActual' : IDL.Int,
  'location' : IDL.Text,
  'daysPaid' : IDL.Int,
  'mobileAllowanceActual' : IDL.Int,
  'mobileAllowancePayable' : IDL.Int,
  'totalEarningsActual' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
});
export const Time = IDL.Int;
export const Employee = IDL.Record({
  'username' : IDL.Text,
  'userId' : EmployeeId,
  'createdAt' : Time,
  'fullName' : IDL.Text,
});
export const RegisterEmployeeInput = IDL.Record({
  'username' : IDL.Text,
  'fullName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPayslip' : IDL.Func([CreatePayslipInput], [PayslipId], []),
  'deletePayslip' : IDL.Func([PayslipId], [], []),
  'getAllPayslips' : IDL.Func([], [IDL.Vec(Payslip)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([EmployeeId], [IDL.Opt(Employee)], ['query']),
  'getPayslip' : IDL.Func([PayslipId], [IDL.Opt(Payslip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'listAllPayslips' : IDL.Func([], [IDL.Vec(Payslip)], ['query']),
  'listPayslipsByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Payslip)],
      ['query'],
    ),
  'registerEmployee' : IDL.Func([RegisterEmployeeInput], [EmployeeId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmployeeId = IDL.Nat;
  const CreatePayslipInput = IDL.Record({
    'month' : IDL.Text,
    'professionTax' : IDL.Int,
    'employeeUsername' : IDL.Text,
    'employeeName' : IDL.Text,
    'ifscCode' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'designation' : IDL.Text,
    'year' : IDL.Nat,
    'businessUnit' : IDL.Text,
    'bankName' : IDL.Text,
    'dateOfJoining' : IDL.Text,
    'insurance' : IDL.Int,
    'incentivePayable' : IDL.Int,
    'employeeId' : EmployeeId,
    'aadharNumber' : IDL.Text,
    'paymentMode' : IDL.Text,
    'basicPayable' : IDL.Int,
    'accountNumber' : IDL.Text,
    'panNo' : IDL.Text,
    'incentiveActual' : IDL.Int,
    'basicActual' : IDL.Int,
    'location' : IDL.Text,
    'daysPaid' : IDL.Int,
    'mobileAllowanceActual' : IDL.Int,
    'mobileAllowancePayable' : IDL.Int,
  });
  const PayslipId = IDL.Nat;
  const Payslip = IDL.Record({
    'month' : IDL.Text,
    'payslipId' : PayslipId,
    'professionTax' : IDL.Int,
    'totalDeductions' : IDL.Int,
    'employeeUsername' : IDL.Text,
    'employeeName' : IDL.Text,
    'ifscCode' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'designation' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'businessUnit' : IDL.Text,
    'bankName' : IDL.Text,
    'dateOfJoining' : IDL.Text,
    'insurance' : IDL.Int,
    'netPayable' : IDL.Int,
    'incentivePayable' : IDL.Int,
    'totalEarningsPayable' : IDL.Int,
    'employeeId' : EmployeeId,
    'aadharNumber' : IDL.Text,
    'paymentMode' : IDL.Text,
    'basicPayable' : IDL.Int,
    'accountNumber' : IDL.Text,
    'panNo' : IDL.Text,
    'incentiveActual' : IDL.Int,
    'basicActual' : IDL.Int,
    'location' : IDL.Text,
    'daysPaid' : IDL.Int,
    'mobileAllowanceActual' : IDL.Int,
    'mobileAllowancePayable' : IDL.Int,
    'totalEarningsActual' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
  });
  const Time = IDL.Int;
  const Employee = IDL.Record({
    'username' : IDL.Text,
    'userId' : EmployeeId,
    'createdAt' : Time,
    'fullName' : IDL.Text,
  });
  const RegisterEmployeeInput = IDL.Record({
    'username' : IDL.Text,
    'fullName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPayslip' : IDL.Func([CreatePayslipInput], [PayslipId], []),
    'deletePayslip' : IDL.Func([PayslipId], [], []),
    'getAllPayslips' : IDL.Func([], [IDL.Vec(Payslip)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([EmployeeId], [IDL.Opt(Employee)], ['query']),
    'getPayslip' : IDL.Func([PayslipId], [IDL.Opt(Payslip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'listAllPayslips' : IDL.Func([], [IDL.Vec(Payslip)], ['query']),
    'listPayslipsByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Payslip)],
        ['query'],
      ),
    'registerEmployee' : IDL.Func([RegisterEmployeeInput], [EmployeeId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };